name: R Package Validation Report
author: Roche
description: |
  A Github Action that generates a validation report for an R package.

inputs:
  report_pkg_dir:
    description: Path to package's root.
    required: false
    default: "."
  report_template_path:
    description: |
      File path of the R markdown template to use for the report.
      The default template is available [here.](./template.qmd)
    required: false
    default: "./template.qmd"
  no_cache:
    description: "Disable github action R dependency caching"
    required: false
    default: "false"
  cache_version:
    description: "Version of the cache. To clean cache bump this version."
    required: false
    default: "v1"
  disable_install_dev_deps:
    description: |
      Disable installation of dev dependencies while
      building the report.
    required: false
    default: "false"
branding: # https://feathericons.com/
  icon: "award"
  color: "blue"

runs:
  using: "composite"
  steps:
    - name: Get R version
      id: r_version
      run: echo "R_VERSION=$(R --version | head -1 | awk '{print $3}')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set R Library home on Linux
      run: |
        mkdir -p ${RUNNER_TEMP}/Library
        echo ".libPaths(c('${RUNNER_TEMP}/Library', .libPaths()))" > ~/.Rprofile
        cat ~/.Rprofile
      shell: bash

    - name: Cache R packages
      if: "contains(inputs.no_cache, 'false')"
      uses: actions/cache@v4
      with:
        path: /home/runner/work/_temp/Library
        key: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}-${{ hashFiles('DESCRIPTION') }}
        restore-keys: ${{ inputs.cache_version }}-${{ runner.os }}-${{ steps.r_version.outputs.R_VERSION }}

    - name: Install dependencies
      run: |
        ${GITHUB_ACTION_PATH}/dependencies.R
        [ ! -f "./template.qmd" ] && cp ${GITHUB_ACTION_PATH}/template.qmd . || echo "./template.qmd already exists"
        MIN_QUARTO_VERSION="1.5.29"
        if [[ "$(echo -e "$(quarto --version)\n${MIN_QUARTO_VERSION}" | sort -V | head -1)" == "${MIN_QUARTO_VERSION}" ]]; then
          echo "✅ Quarto CLI version sufficient (>= ${MIN_QUARTO_VERSION})"
          echo "Quarto CLI version: $(quarto --version)"
        else
          echo "❌ Quarto CLI version insufficient (< ${MIN_QUARTO_VERSION})"
          apt-get update
          apt-get install -qy wget jq
          export QUARTO_VERSION="1.5.37"
          echo "Downloading and installing Quarto CLI version ${QUARTO_VERSION}"
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
          dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb
          echo "New Quarto CLI version: $(quarto --version)"
        fi
      shell: bash

    - name: Run report generator
      id: report-generator
      run: |
        ${GITHUB_ACTION_PATH}/report-generator.R
      shell: bash
      env:
        # Composite action doesn't set inputs as env vars.
        # We need to do this manually...
        INPUT_REPORT_PKG_DIR: ${{ inputs.report_pkg_dir }}
        INPUT_REPORT_TEMPLATE_PATH: ${{ inputs.report_template_path }}
        DISABLE_INSTALL_DEV_DEPS: ${{ inputs.disable_install_dev_deps }}
